<a href="https://colab.research.google.com/github/prashamsalohanii/Accessoriesshop/blob/starter/Diabetiesprediction_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [12]:
diabetes_dataset=pd.read_csv('/content/diabetes.csv')

In [13]:
diabetes_dataset.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [14]:
diabetes_dataset.shape

(769, 9)

In [15]:
diabetes_dataset.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,769.000000,769.000000,769.000000,769.000000,769.000000,769.000000,769.000000,769.000000,769.000000
mean,3.840052,120.897269,69.115735,20.509753,79.697009,31.998179,0.471590,33.269181,0.349805
std,3.370237,31.951886,19.345296,15.959020,115.203999,7.880557,0.331208,11.778737,0.477219
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.244000,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,29.000000,32.000000,0.371000,29.000000,0.000000
75%,6.000000,140.000000,80.000000,32.000000,127.000000,36.600000,0.626000,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [17]:
diabetes_dataset['Outcome'].value_counts()

Outcome
0    500
1    269
Name: count, dtype: int64

In [18]:
diabetes_dataset.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,109.980000,68.184000,19.664000,68.792000,30.30420,0.429734,31.190000
1,4.847584,141.189591,70.847584,22.081784,99.966543,35.14684,0.549390,37.133829

In [19]:
X=diabetes_dataset.drop(columns='Outcome',axis=1)
Y=diabetes_dataset['Outcome']

In [20]:
scaler=StandardScaler()
scaler.fit(X)
standardized_data=scaler.transform(X)

In [21]:
print(standardized_data)

[[ 0.64130614  0.84878777  0.14919091 ...  0.20339465  0.46952637
   1.42135003]
 [-0.84323457 -1.12421007 -0.16116385 ... -0.68544558 -0.36432984
  -0.19277598]
 [ 1.23512243  1.94489768 -0.26461544 ... -1.10447026  0.60548119
  -0.10782198]
 ...
 [-0.84323457  0.15980439 -0.47151862 ... -0.24102547 -0.37037227
   1.16648803]
 [-0.84323457 -0.87367066  0.04573932 ... -0.20293231 -0.47309369
  -0.87240799]
 [-1.14014271  0.06585212  0.40781989 ...  0.54623302 -0.66343044
   1.84612003]]

In [22]:
x=standardized_data
y=diabetes_dataset['Outcome']

In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y,random_state=2)

In [24]:
classifier=svm.SVC(kernel='linear')
classifier.fit(x_train,y_train)

SVC(kernel='linear')

In [25]:
x_train_prediction=classifier.predict(x_train)
training_data_accuracy=accuracy_score(x_train_prediction,y_train)

In [26]:
print('Accuracy score of the training data : ', training_data_accuracy)

Accuracy score of the training data :  0.7886178861788617

In [27]:
x_test_prediction=classifier.predict(x_test)
test_data_accuracy=accuracy_score(x_test_prediction,y_test)

In [28]:
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the test data :  0.7597402597402597

In [30]:
input_data = (5,166,72,19,175,25.8,0.587,51)
input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
standardized_data = scaler.transform(input_data_reshaped)
print(standardized_data)
prediction = classifier.predict(standardized_data)
print(prediction)
if (prediction[0] == 0):
  print('The person is not diabetic')
else:
  print('The person is diabetic')

[[ 0.344398    1.41250144  0.14919091 -0.09466342  0.82779259 -0.78702732
   0.34867765  1.50630403]]
[1]
The person is diabetic

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(